language: ruby
sudo: false
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head
  - jruby-9.1.16.0
  - jruby-head
before_script:
  - unset JRUBY_OPTS
  - unset _JAVA_OPTIONS
script: ruby -Ilib exe/rake
